name: Monitor Public GitHub Repo Changes

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write

jobs:
  monitor_repo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Get latest commit from public repo
      run: |
        curl -s https://api.github.com/repos/FiveNightsTD/Stats/commits?per_page=1 > latest_commit.json
        COMMIT_SHA=$(jq -r '.[0].sha' latest_commit.json)
        COMMIT_MESSAGE=$(jq -r '.[0].commit.message' latest_commit.json)
        COMMIT_AUTHOR=$(jq -r '.[0].commit.author.name' latest_commit.json)
        COMMIT_URL=$(jq -r '.[0].html_url' latest_commit.json)

        # Set environment variables
        echo "commit_sha=$COMMIT_SHA" >> $GITHUB_ENV
        echo "commit_message=$COMMIT_MESSAGE" >> $GITHUB_ENV
        echo "commit_author=$COMMIT_AUTHOR" >> $GITHUB_ENV
        echo "commit_url=$COMMIT_URL" >> $GITHUB_ENV

    - name: Check for new commit
      id: check_commit
      run: |
        # Check if the last_commit_sha.txt file exists
        if [ -f last_commit_sha.txt ]; then
          LAST_COMMIT_SHA=$(cat last_commit_sha.txt)
          echo "Last known commit SHA: $LAST_COMMIT_SHA"
        else
          LAST_COMMIT_SHA=""
          echo "last_commit_sha.txt not found. This is the first run."
        fi

        echo "Current commit SHA: ${{ env.commit_sha }}"

        # Compare current commit SHA with the last commit SHA
        if [ "$LAST_COMMIT_SHA" != "${{ env.commit_sha }}" ]; then
          echo "New commit detected!"
          echo "${{ env.commit_sha }}" > last_commit_sha.txt
          echo "::set-output name=new_commit::true"  # Indicate a new commit was found
        else
          echo "No new commits."
          echo "::set-output name=new_commit::false"  # No new commit found
          exit 0  # Exit the workflow if no new commits
        fi

    - name: Send notification to Discord if new commit
      if: steps.check_commit.outputs.new_commit == 'true'  # Only run if there's a new commit
      run: |
        curl -H "Content-Type: application/json" \
        -X POST \
        -d "{\"content\": \"<@787616132176937020> New commit by ${{ env.commit_author }}: ${{ env.commit_message }}. [View Commit](${{ env.commit_url }})\"}" \
        ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Commit last commit SHA
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add last_commit_sha.txt
        git commit -m "Update last commit SHA to ${{ env.commit_sha }}" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Tadtadtad2018/FNTD-Stat-Fetcher.git

